blueprint:
  name: "Frank Energie - Smart Battery Manager v1.7.1 (Dynamic Reserve)- DEV"
  description: >
    **Fix v1.6.5:**
    - Peak Reserve is nu gekoppeld aan een Input Number (Helper) voor dynamische sturing.
    - Hierdoor kan een andere automation (op basis van historie) de reserve bepalen.
    
    STRATEGY: Skim the top first, dump the rest at max price.
  domain: automation
  input:
    # --- GENERAL ---
    language:
      name: "Language / Taal"
      default: "nl"
      selector:
        select:
          options:
            - label: "English"
              value: "en"
            - label: "Nederlands"
              value: "nl"

    # --- ENTITIES ---
    battery_reserve_switch:
      name: "Switch: Force Charge"
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: "Sensor: Battery SoC"
      selector:
        entity:
          domain: sensor
          device_class: battery
    target_soc_number:
      name: "Entity: Target SoC"
      selector:
        entity:
          domain: number
    frank_price_sensor:
      name: "Sensor: Frank Energy Prices"
      selector:
        entity:
          domain: sensor
    last_price_helper:
      name: "Helper: Last Purchase Price"
      selector:
        entity:
          domain: input_number

    # --- DYNAMIC RESERVE ---
    peak_reserve_helper:
      name: "Helper: Peak Reserve (kWh)"
      description: "Selecteer de Input Number helper die bepaalt hoeveel kWh gereserveerd moet blijven voor de Top Piek."
      selector:
        entity:
          domain: input_number

    # --- STRATEGY ---
    peak_hours_count:
      name: "Top Peak Window (Hours)"
      default: 3
      selector:
        number:
          min: 1
          max: 6
    min_discharge_margin:
      name: "Min. Discharge Profit (%)"
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    # --- GUARANTEES ---
    min_base_soc:
      name: "Absolute Minimum SoC (%)"
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    # --- NOTIFICATIONS ---
    boost_switch:
      name: "Switch: Manual Boost"
      default: []
      selector:
        entity:
          domain: input_boolean
    notify_device:
      name: "Notification Device"
      default: []
      selector:
        device:
          integration: mobile_app

    # --- TARGETS ---
    target_soc_winter:
      name: "Target SoC (Winter/Cloudy)"
      default: 90
      selector:
        number:
          min: 10
          max: 100
    target_soc_summer:
      name: "Target SoC (Summer/Sunny)"
      default: 30
      selector:
        number:
          min: 10
          max: 100
    summer_solar_threshold:
      name: "Summer Solar Threshold (kWh)"
      default: 15
      selector:
        number:
          min: 0
          max: 100

    # --- SYSTEM ---
    solar_forecast_today:
      name: "Sensor: Solar Forecast Today"
      selector:
        entity:
          domain: sensor
    solar_forecast_tomorrow:
      name: "Sensor: Solar Forecast Tomorrow"
      selector:
        entity:
          domain: sensor
    battery_capacity_kwh:
      name: "Battery Capacity (kWh)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 0.1
    charge_power_kw:
      name: "Charge Speed (kW)"
      default: 3.0
      selector:
        number:
          min: 0.1
          max: 22
          step: 0.1
    safety_factor:
      name: "BMS Safety Factor"
      default: 2.0
      selector:
        number:
          min: 1.0
          max: 4.0
          step: 0.1
    max_price_cap:
      name: "Absolute Max Price (â‚¬)"
      default: 0.35
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.01

    # --- TIMING ---
    report_time_evening:
      name: "Report Time (Evening)"
      default: "21:30:00"
      selector:
        time:
    report_time_morning:
      name: "Report Time (Morning)"
      default: "08:00:00"
      selector:
        time:

# Trigger Variables
trigger_variables:
  boost_entity: !input boost_switch

trigger:
  - platform: time_pattern
    minutes: "0"
    id: "timer"
  - platform: time_pattern
    minutes: "30"
    id: "timer"
  - platform: time
    at: !input report_time_evening
    id: "report"
  - platform: time
    at: !input report_time_morning
    id: "report"
  - platform: state
    entity_id: !input frank_price_sensor
    id: "price_change"
  - platform: template
    value_template: "{{ boost_entity != [] and is_state(boost_entity, 'on') }}"
    id: "boost"

action:
  # --- STEP 1: MAP INPUTS ---
  - variables:
      language: !input language
      conf_soc_sensor: !input battery_soc_sensor
      conf_price_sensor: !input frank_price_sensor
      conf_last_price: !input last_price_helper
      conf_boost: !input boost_switch
      conf_notify: !input notify_device
      conf_target_num: !input target_soc_number
      conf_switch: !input battery_reserve_switch
      
      # DYNAMIC RESERVE (via Helper)
      conf_reserve_helper: !input peak_reserve_helper
      p_reserve_kwh: "{{ states(conf_reserve_helper) | float(4.0) }}" 

      # Settings
      p_peak_count: !input peak_hours_count
      p_min_discharge: !input min_discharge_margin
      p_bat_cap: !input battery_capacity_kwh
      p_charge_kw: !input charge_power_kw
      p_safety: !input safety_factor
      p_max_cap: !input max_price_cap
      p_min_base_soc: !input min_base_soc
      
      # Targets
      t_winter: !input target_soc_winter
      t_summer: !input target_soc_summer
      t_solar_th: !input summer_solar_threshold
      s_sol_today: !input solar_forecast_today
      s_sol_tom: !input solar_forecast_tomorrow

  # --- STEP 2: READ STATES ---
  - variables:
      current_soc: "{{ states(conf_soc_sensor) | float(0) }}"
      current_price: "{{ states(conf_price_sensor) | float(0) }}"
      last_paid_price: "{{ states(conf_last_price) | float(0) }}"
      is_boost_active: "{{ conf_boost != [] and is_state(conf_boost, 'on') }}"
      has_notify_device: "{{ conf_notify != [] }}"
      now_ts: "{{ as_timestamp(now()) }}"

  # --- STEP 3: PARSE DATA ---
  - variables:
      raw: "{{ state_attr(conf_price_sensor, 'prices') }}"
      prices_json: >-
        {% if raw %}
          {% set text = raw | string %}
          {% set matches = text | regex_findall(
            "datetime\\.datetime\\((\\d+), (\\d+), (\\d+), (\\d+), (\\d+).*?price': ([0-9.]+)"
          ) %}
          [
          {%- for m in matches %}
            {% set y = m[0]|int %}
            {% set mo = m[1]|int %}
            {% set d = m[2]|int %}
            {% set h = m[3]|int %}
            {% set mn = m[4]|int %}
            {% set price = m[5]|float %}
            {% set raw_dt_str = "%04d-%02d-%02dT%02d:%02d:00" | format(y, mo, d, h, mn) %}
            {% set ts_val = as_timestamp(raw_dt_str) %}
            {
              "local_hour": {{ h }},
              "day_str": "{{ 'Vandaag' if d == now().day else 'Morgen' }}",
              "ts": {{ ts_val }},
              "price": {{ price }}
            }{{ "," if not loop.last }}
          {%- endfor %}
          ]
        {% else %} [] {% endif %}

  # --- STEP 4: ANALYZE PEAKS ---
  - variables:
      filtered_data: >-
        {% set output = namespace(short_term_prices=[], all_today=[]) %}
        {% set rolling_cutoff = now_ts + (18 * 3600) %}
        {% if prices_json %}
           {% for item in prices_json %}
              {# Collect future prices for next 18 hours to find TOP peak #}
              {% if item.ts >= now_ts and item.ts <= rolling_cutoff %}
                  {% set output.short_term_prices = output.short_term_prices + [item.price] %}
              {% endif %}
              {# Collect ALL prices for global low calculation #}
              {% if item.ts >= (now_ts - 3600) %}
                  {% set output.all_today = output.all_today + [item.price] %}
              {% endif %}
           {% endfor %}
        {% endif %}
        {% set sorted_future = output.short_term_prices | sort(reverse=True) %}
        {% set pk_count = p_peak_count | int %}
        {% set peak_threshold = 999 %}
        {% if sorted_future | length >= pk_count %}
           {% set peak_threshold = sorted_future[pk_count - 1] %}
        {% elif sorted_future | length > 0 %}
           {% set peak_threshold = sorted_future | last %}
        {% endif %}
        {"threshold": {{ peak_threshold }}, "all_prices": {{ output.all_today }} }

  # --- STEP 5: CALCULATE LOGIC ---
  - variables:
      sorted_all: "{{ filtered_data.all_prices | sort }}"
      
      # 1. RESERVE CALCULATION (Dynamic from Helper)
      reserve_soc_pct: "{{ (p_reserve_kwh | float / p_bat_cap | float) * 100 }}"
      
      # 2. IS THIS A SUPER PEAK?
      is_super_peak: "{{ current_price >= filtered_data.threshold | float }}"
      
      # 3. DISCHARGE LIMIT
      discharge_target_soc: >-
        {% if is_super_peak %} {{ p_min_base_soc }}
        {% else %} {{ [reserve_soc_pct, p_min_base_soc|float] | max }}
        {% endif %}

      # 4. PROFIT CHECK
      discharge_start_price: "{{ last_paid_price * (1 + (p_min_discharge | float / 100)) }}"

      # 5. CHARGE LOGIC
      forecast_tomorrow_val: "{{ states(s_sol_tom) | float(0) }}"
      relevant_solar: >-
        {% if now().hour >= 14 %} {{ forecast_tomorrow_val }}
        {% else %} {{ states(s_sol_today) | float(0) }}
        {% endif %}
      dynamic_target_soc: >-
        {% if relevant_solar | float > t_solar_th | float %} {{ t_summer }}
        {% else %} {{ t_winter }}
        {% endif %}
      
      charge_limit_strict: >-
        {% set deficit = dynamic_target_soc | float - current_soc %}
        {% if deficit > 0 %}
           {% set kwh_needed = (deficit / 100.0) * p_bat_cap | float %}
           {% set hours_needed = (kwh_needed / p_charge_kw | float * p_safety | float) | round(0, 'ceil') | int %}
           {% if sorted_all | length > 0 %}
             {% set idx = (hours_needed - 1) if (hours_needed - 1) < sorted_all|length else (sorted_all|length - 1) %}
             {{ sorted_all[idx] }}
           {% else %} -999 {% endif %}
        {% else %} -999 {% endif %}

  # --- STEP 6: EXECUTION ---
  - choose:
      # --- 1. REPORT ---
      - alias: "1. Send Report"
        conditions:
          - condition: trigger
            id: "report"
        sequence:
          - if:
              - condition: template
                value_template: "{{ has_notify_device }}"
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                message: >-
                  {% if language == 'nl' %}
                    ðŸ“Š **Status**
                    SoC: {{ current_soc }}% | Reserve: {{ p_reserve_kwh }} kWh
                    
                    ðŸ’° **Prijzen**
                    Nu: â‚¬{{ current_price | round(3) }}
                    Laadgrens: â‚¬{{ charge_limit_strict | round(3) }}
                    Ontlaadgrens: â‚¬{{ discharge_start_price | round(3) }}
                    
                    â­ **Pieken**
                    Super Piek: > â‚¬{{ filtered_data.threshold | round(3) }}
                    Is Super Piek? {{ 'JA' if is_super_peak else 'NEE' }}
                    Ontlaadlimiet nu: {{ discharge_target_soc | round(0) }}%
                  {% else %}
                    Status: {{ current_soc }}%
                  {% endif %}

      # --- 2. BOOST ---
      - alias: "2. Boost Mode"
        conditions:
          - condition: template
            value_template: "{{ is_boost_active }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: !input target_soc_number
            data:
              value: 100
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch

      # --- 3. SMART CHARGING ---
      - alias: "3. Smart Charging"
        conditions:
          - condition: template
            value_template: "{{ current_price <= (charge_limit_strict + 0.001) }}"
          - condition: template
            value_template: "{{ current_soc < dynamic_target_soc | float }}"
          - condition: template
            value_template: "{{ current_price < p_max_cap | float }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: !input target_soc_number
            data:
              value: "{{ dynamic_target_soc }}"
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch
          - service: input_number.set_value
            target:
              entity_id: !input last_price_helper
            data:
              value: "{{ current_price }}"

      # --- 4. SMART DISCHARGING ---
      - alias: "4. Smart Discharging"
        conditions:
          - condition: template
            value_template: "{{ current_price >= discharge_start_price }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ current_soc > discharge_target_soc }}"
            then:
              - service: switch.turn_off
                target:
                 entity_id: !input battery_reserve_switch
            else:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - service: number.set_value
                target:
                  entity_id: !input target_soc_number
                data:
                  value: "{{ current_soc | int }}"

      # --- 5. SMART HOLD ---
      - alias: "5. Smart Hold"
        conditions:
          - condition: template
            value_template: "{{ current_price > charge_limit_strict }}"
          - condition: template
            value_template: "{{ current_price < discharge_start_price }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch
          - service: number.set_value
            target:
              entity_id: !input target_soc_number
            data:
              value: "{{ current_soc | int }}"

    default:
      - service: switch.turn_off
        target:
          entity_id: !input battery_reserve_switch

mode: single