blueprint:
  name: "Frank Energie - Smart Battery Manager v1.6.2.5 (Backup Soc)"
  description: >
    **Fix v1.6.1:**
    - Syntaxfout in 'default' actie opgelost.
    - Dayround logica (24/7) actief.
    - Rolling Peak Analysis (voorkomt laden voor dure prijzen van morgen).
    - de noodzaak dat het systeem de backup soc aanpast bij uitzetten van de reserve weggehaald.

    
    STRATEGY: Profit & Hardware Protection.
  domain: automation
  input:
    # --- GENERAL ---
    language:
      name: "Language / Taal"
      default: "nl"
      selector:
        select:
          options:
            - label: "English"
              value: "en"
            - label: "Nederlands"
              value: "nl"

    # --- ENTITIES ---
    battery_reserve_switch:
      name: "Switch: Force Charge"
      description: "De schakelaar die force-charge of 'hold' activeert."
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: "Sensor: Battery SoC"
      selector:
        entity:
          domain: sensor
          device_class: battery
    target_soc_number:
      name: "Entity: Target SoC"
      description: "Het getal dat bepaalt tot hoe ver de batterij laadt."
      selector:
        entity:
          domain: number
    frank_price_sensor:
      name: "Sensor: Frank Energy Prices"
      description: "De sensor met attributen 'prices' (zoals de Zonneplan/Frank integratie)."
      selector:
        entity:
          domain: sensor
    last_price_helper:
      name: "Helper: Last Purchase Price"
      description: "Input number om op te slaan voor welke prijs er geladen is (voor winstberekening)."
      selector:
        entity:
          domain: input_number

    # --- STRATEGY ---
    peak_hours_count:
      name: "Peak Analysis Window"
      description: "Hoeveel duurste uren tellen mee voor het gemiddelde?"
      default: 3
      selector:
        number:
          min: 1
          max: 6
    buffer_discount_percentage:
      name: "Buffer Discount (%)"
      description: "Hoeveel % moet de prijs onder de piek liggen om te laden?"
      default: 40
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "%"
    min_discharge_margin:
      name: "Min. Discharge Profit (%)"
      description: "Minimale winstmarge t.o.v. laadprijs om te ontladen."
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    # --- GUARANTEES ---
    min_base_soc:
      name: "Absolute Minimum SoC (%)"
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    # --- NOTIFICATIONS ---
    boost_switch:
      name: "Switch: Manual Boost"
      default: []
      selector:
        entity:
          domain: input_boolean
    notify_device:
      name: "Notification Device"
      default: []
      selector:
        device:
          integration: mobile_app

    # --- TARGETS ---
    target_soc_winter:
      name: "Target SoC (Winter/Cloudy)"
      default: 90
      selector:
        number:
          min: 10
          max: 100
    target_soc_summer:
      name: "Target SoC (Summer/Sunny)"
      default: 30
      selector:
        number:
          min: 10
          max: 100
    summer_solar_threshold:
      name: "Summer Solar Threshold (kWh)"
      description: "Als voorspelling hoger is dan dit, gebruik Summer Target."
      default: 15
      selector:
        number:
          min: 0
          max: 100

    # --- SYSTEM ---
    solar_forecast_today:
      name: "Sensor: Solar Forecast Today"
      selector:
        entity:
          domain: sensor
    solar_forecast_tomorrow:
      name: "Sensor: Solar Forecast Tomorrow"
      selector:
        entity:
          domain: sensor
    battery_capacity_kwh:
      name: "Battery Capacity (kWh)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 0.1
    charge_power_kw:
      name: "Charge Speed (kW)"
      default: 3.0
      selector:
        number:
          min: 0.1
          max: 22
          step: 0.1
    safety_factor:
      name: "BMS Safety Factor"
      description: "Vermenigvuldiging laadtijd (1.5 = 50% extra tijd inplannen)."
      default: 1.5
      selector:
        number:
          min: 1.0
          max: 4.0
          step: 0.1
    max_price_cap:
      name: "Absolute Max Price (€)"
      description: "Boven deze prijs NOOIT laden, ook niet als batterij leeg is."
      default: 0.35
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.01

    # --- TIMING (Reporting Only) ---
    report_time_evening:
      name: "Report Time (Evening)"
      default: "21:30:00"
      selector:
        time:
    report_time_morning:
      name: "Report Time (Morning)"
      default: "08:00:00"
      selector:
        time:

# Trigger Variables
trigger_variables:
  boost_entity: !input boost_switch

trigger:
  - platform: time_pattern
    minutes: "/5"
    id: "timer"
  - platform: time
    at: !input report_time_evening
    id: "report"
  - platform: time
    at: !input report_time_morning
    id: "report"
  - platform: state
    entity_id: !input frank_price_sensor
    id: "price_change"
  - platform: template
    value_template: "{{ boost_entity != [] and is_state(boost_entity, 'on') }}"
    id: "boost"

action:
  # --- STEP 1: MAP INPUTS TO VARIABLES ---
  - variables:
      # Entities
      conf_soc_sensor: !input battery_soc_sensor
      conf_price_sensor: !input frank_price_sensor
      conf_last_price: !input last_price_helper
      conf_boost: !input boost_switch
      conf_notify: !input notify_device
      conf_target_num: !input target_soc_number
      conf_switch: !input battery_reserve_switch
      
      # Settings
      p_peak_count: !input peak_hours_count
      p_buffer_disc: !input buffer_discount_percentage
      p_min_discharge: !input min_discharge_margin
      p_bat_cap: !input battery_capacity_kwh
      p_charge_kw: !input charge_power_kw
      p_safety: !input safety_factor
      p_max_cap: !input max_price_cap
      p_min_base_soc: !input min_base_soc
      
      # Targets & Solar
      t_winter: !input target_soc_winter
      t_summer: !input target_soc_summer
      t_solar_th: !input summer_solar_threshold
      s_sol_today: !input solar_forecast_today
      s_sol_tom: !input solar_forecast_tomorrow

  # --- STEP 2: READ STATES & TIME ---
  - variables:
      current_soc: "{{ states(conf_soc_sensor) | float(0) }}"
      current_price: "{{ states(conf_price_sensor) | float(0) }}"
      last_paid_price: "{{ states(conf_last_price) | float(0) }}"
      is_boost_active: "{{ conf_boost != [] and is_state(conf_boost, 'on') }}"
      has_notify_device: "{{ conf_notify != [] }}"
      now_ts: "{{ as_timestamp(now()) }}"

  # --- STEP 3: PARSE DATA ---
  - variables:
      raw: "{{ state_attr(conf_price_sensor, 'prices') }}"
      prices_json: >-
        {% if raw %}
          {% set text = raw | string %}
          {% set matches = text | regex_findall(
            "datetime\\.datetime\\((\\d+), (\\d+), (\\d+), (\\d+), (\\d+).*?price': ([0-9.]+)"
          ) %}
          [
          {%- for m in matches %}
            {% set y = m[0]|int %}
            {% set mo = m[1]|int %}
            {% set d = m[2]|int %}
            {% set h = m[3]|int %}
            {% set mn = m[4]|int %}
            {% set price = m[5]|float %}
            {% set raw_dt_str = "%04d-%02d-%02dT%02d:%02d:00" | format(y, mo, d, h, mn) %}
            {% set ts_val = as_timestamp(raw_dt_str) %}
            {
              "local_hour": {{ h }},
              "day_str": "{{ 'Vandaag' if d == now().day else 'Morgen' }}",
              "ts": {{ ts_val }},
              "price": {{ price }}
            }{{ "," if not loop.last }}
          {%- endfor %}
          ]
        {% else %} [] {% endif %}

  # --- STEP 4: FILTER & ANALYZE (Sequential Logic) ---
  - variables:
      filtered_data: >-
        {% set output = namespace(all_prices=[], future_slots=[], short_term_prices=[]) %}
        {% set history_cutoff = now_ts - 3600 %}
        {% set rolling_cutoff = now_ts + (12 * 3600) %}
        
        {% if prices_json %}
           {% for item in prices_json %}
              {# Keep strict history limit #}
              {% if item.ts >= history_cutoff %}
                  {% set output.all_prices = output.all_prices + [item.price] %}
                  {% set output.future_slots = output.future_slots + [item] %}
                  
                  {# Rolling window for PEAK logic (Next 12h only) #}
                  {% if item.ts <= rolling_cutoff %}
                     {% set output.short_term_prices = output.short_term_prices + [item.price] %}
                  {% endif %}
              {% endif %}
           {% endfor %}
        {% endif %}
        
        {# Calculate Peak based on SHORT TERM only to avoid tomorrow's high prices trigger today #}
        {% set pk_count = p_peak_count | int %}
        {% set sorted_short = output.short_term_prices | sort(reverse=True) %}
        {% set rolling_peak = 0 %}
        
        {% if sorted_short | length > 0 %}
           {% set count = [sorted_short|length, pk_count] | min %}
           {% set rolling_peak = (sorted_short[:count] | sum / count) %}
        {% endif %}

        {"all": {{ output.all_prices }}, "slots": {{ output.future_slots }}, "peak": {{ rolling_peak }} }

  # --- STEP 5: DERIVED VARIABLES ---
  - variables:
      sorted_all: "{{ filtered_data.all | sort }}"
      
      # Determine Limits
      relevant_peak_price: "{{ filtered_data.peak }}"
      buffer_limit: "{{ relevant_peak_price | float * (1 - (p_buffer_disc | float / 100)) }}"

      # Solar & Targets
      forecast_tomorrow_val: "{{ states(s_sol_tom) | float(0) }}"
      relevant_solar: >-
        {% if now().hour >= 14 %} {{ forecast_tomorrow_val }}
        {% else %} {{ states(s_sol_today) | float(0) }}
        {% endif %}
      
      dynamic_target_soc: >-
        {% if relevant_solar | float > t_solar_th | float %} {{ t_summer }}
        {% else %} {{ t_winter }}
        {% endif %}

      # Charge Ceiling STRICT (Global low prices)
      charge_limit_strict: >-
        {% set deficit = dynamic_target_soc | float - current_soc %}
        {% if deficit > 0 %}
           {% set kwh_needed = (deficit / 100.0) * p_bat_cap | float %}
           {% set hours_needed = (kwh_needed / p_charge_kw | float * p_safety | float) | round(0, 'ceil') | int %}
           
           {% if sorted_all | length > 0 %}
             {% set idx = (hours_needed - 1) if (hours_needed - 1) < sorted_all|length else (sorted_all|length - 1) %}
             {{ sorted_all[idx] }}
           {% else %} -999 {% endif %}
        {% else %} -999 {% endif %}

      # Discharge Threshold
      discharge_start_price: "{{ last_paid_price * (1 + (p_min_discharge | float / 100)) }}"

  # --- STEP 6: EXECUTION ---
  - choose:
      # --- PRIORITY 1: REPORTING ---
      - alias: "1. Send Report"
        conditions:
          - condition: trigger
            id: "report"
        sequence:
          - if:
              - condition: template
                value_template: "{{ has_notify_device }}"
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                message: >-
                  {% if language == 'nl' %}
                    📊 **Dayround Status**
                    
                    🔋 **Batterij**
                    SoC: {{ current_soc }}% | Doel: {{ dynamic_target_soc }}%
                    
                    💰 **Drempels**
                    Strikt (<): €{{ charge_limit_strict | round(3) }}
                    Buffer (<): €{{ buffer_limit | round(3) }}
                    12u Piek Ref: €{{ relevant_peak_price | round(3) }}
                    
                    🕒 **Geplande Acties**
                    {%- set ns_list = namespace(found=[]) %}
                    {%- for item in filtered_data.slots %}
                      {%- if item.ts < (now_ts + (24*3600)) %}
                        {%- if item.price <= charge_limit_strict %}
                          {%- set ns_list.found = ns_list.found + [item.day_str ~ " " ~ item.local_hour ~ ":00 (€" ~ item.price|round(3) ~ ") [Strikt]"] %}
                        {%- elif item.price <= buffer_limit and current_soc < dynamic_target_soc %}
                          {%- set ns_list.found = ns_list.found + [item.day_str ~ " " ~ item.local_hour ~ ":00 (€" ~ item.price|round(3) ~ ") [Buffer]"] %}
                        {%- endif %}
                      {%- endif %}
                    {%- endfor %}
                    {{ ns_list.found | join('\n') if ns_list.found else "Geen actie gepland in komende 24u." }}
                  {% else %}
                    📊 **Dayround Report**
                    Status: {{ current_soc }}% / {{ dynamic_target_soc }}%
                  {% endif %}

      # --- PRIORITY 2: BOOST ---
      - alias: "2. Boost Mode"
        conditions:
          - condition: template
            value_template: "{{ is_boost_active }}"
        sequence:
          - service: number.set_value
            target:
              entity_id: !input target_soc_number
            data:
              value: 100
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch

      # --- PRIORITY 3: EMERGENCY ---
      - alias: "3. Emergency Charge"
        conditions:
          - condition: template
            value_template: "{{ current_soc < p_min_base_soc | float }}"
          - condition: template
            value_template: "{{ current_price < (p_max_cap | float * 1.5) }}"
        sequence:
        # --- CHECK & SET SOC ---
          - if:
              - condition: template
                # Check: Is het verschil tussen huidige instelling en wens groter dan 0.1?
                value_template: "{{ (states(conf_target_num)|float(0) - dynamic_target_soc|float)|abs > 0.1 }}"
            then:
              - service: number.set_value
                target:
                  entity_id: !input target_soc_number
                data:
                  value: "{{ p_min_base_soc }}"
          - if:
              - condition: template
                value_template: "{{ is_state(conf_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
          - service: input_number.set_value
            target:
              entity_id: !input last_price_helper
            data:
              value: "{{ current_price }}"

      # --- PRIORITY 4: SMART CHARGING (24/7) ---
      - alias: "4. Smart Charging"
        conditions:
          - condition: or
            conditions:
              # A. STRICT
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ current_price <= charge_limit_strict }}"
                  - condition: template
                    value_template: "{{ current_soc < dynamic_target_soc | float }}"
                  - condition: template
                    value_template: "{{ current_price < p_max_cap | float }}"
              # B. BUFFER
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ current_price <= buffer_limit }}"
                  - condition: template
                    value_template: "{{ current_soc < dynamic_target_soc | float }}"
                  - condition: template
                    value_template: "{{ current_price < p_max_cap | float }}"
        sequence:
              # --- CHECK & SET SOC ---
          - if:
              - condition: template
                # Check: Is het verschil tussen huidige instelling en wens groter dan 0.1?
                value_template: "{{ (states(conf_target_num)|float(0) - dynamic_target_soc|float)|abs > 0.5 }}"
            then:
              - service: number.set_value
                target:
                  entity_id: !input target_soc_number
                data:
                  value: "{{ dynamic_target_soc }}"
          - if:
              - condition: template
                value_template: "{{ is_state(conf_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
          - service: input_number.set_value
            target:
              entity_id: !input last_price_helper
            data:
              value: "{{ current_price }}"
          - if:
              - condition: template
                value_template: "{{ has_notify_device }}"
              - condition: template
                value_template: >-
                  {% if states[conf_switch].last_changed %}
                    {{ (as_timestamp(now()) - as_timestamp(states[conf_switch].last_changed)) > 3600 }}
                  {% else %} true {% endif %}
            then:
              - domain: mobile_app
                type: notify
                device_id: !input notify_device
                message: >-
                  🟢 Start Laden (€{{ current_price | round(3) }})
                  Ref 12u Piek: €{{ relevant_peak_price | round(3) }}

      # --- PRIORITY 5: DISCHARGING ---
      - alias: "5. Discharging"
        conditions:
          - condition: template
            value_template: "{{ current_price >= discharge_start_price }}"
        sequence:
        - if:
              - condition: template
                value_template: "{{ is_state(conf_switch, 'on') }}"
          then:
              - service: switch.turn_off
                target:
                 entity_id: !input battery_reserve_switch
      # --- PRIORITY 6: SMART HOLD ---
      - alias: "6. Smart Hold"
        conditions:
          - condition: template
            value_template: "{{ current_price > charge_limit_strict }}"
          - condition: template
            value_template: "{{ current_price < discharge_start_price }}"
          - condition: template
            value_template: "{{ current_soc > p_min_base_soc | float }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch
          - if:
              - condition: template
                value_template: "{{ (states(conf_target_num)|float(0) - current_soc) > 1 }}"
            then:
              - service: number.set_value
                target:
                  entity_id: !input target_soc_number
                data:
                  value: "{{ current_soc | int }}"
              - if:
                  - condition: template
                    value_template: "{{ has_notify_device }}"
                  - condition: template
                    value_template: >-
                       {% if states[conf_switch].last_changed %}
                         {{ (as_timestamp(now()) - as_timestamp(states[conf_switch].last_changed)) > 3600 }}
                       {% else %} true {% endif %}
                then:
                  - domain: mobile_app
                    type: notify
                    device_id: !input notify_device
                    message: "🟡 Smart Hold (Prijs neutraal)"

    # --- PRIORITY 7: DEFAULT / ECO (House Consumption) ---
    # Dit is de 'else' als geen van bovenstaande voorwaarden waar is.
    # Hier zetten we de switch UIT zodat de batterij het huis kan voeden (Eco mode).
    default:
      - service: switch.turn_off
        target:
          entity_id: !input battery_reserve_switch

mode: single