blueprint:
  name: Slimme batterij laadplanning dynamische tijden
  description: Laadt de batterij automatisch op de goedkoopste momenten van de dag, gebaseerd op actuele prijs en gemiddelde, met vrije tijdsblokken.
  domain: automation
  input:
    battery_reserve_switch:
      name: Reserve mode switch
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: Batterij SOC sensor
      selector:
        entity:
          domain: sensor
    electricity_price_sensor:
      name: Huidige elektriciteitsprijs
      selector:
        entity:
          domain: sensor
    solar_forecast_sensor:
      name: Verwachte zonopbrengst (kWh)
      default: ""
      selector:
        entity:
          domain: sensor
    min_solar_day:
      name: Minimale zon kWh voor overdag
      default: 8
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: "kWh"
    load_start_hour:
      name: Start uur controleren
      description: Vanaf welk uur mag laden starten
      default: 0
      selector:
        number:
          min: 0
          max: 23
    load_end_hour:
      name: Eind uur controleren
      description: Tot welk uur mag laden
      default: 23
      selector:
        number:
          min: 0
          max: 23

variables:
  battery_reserve_switch: !input battery_reserve_switch
  battery_soc_sensor: !input battery_soc_sensor
  electricity_price_sensor: !input electricity_price_sensor
  solar_forecast_sensor: !input solar_forecast_sensor
  min_solar_day: !input min_solar_day
  load_start_hour: !input load_start_hour
  load_end_hour: !input load_end_hour

trigger:
  - platform: time_pattern
    minutes: "/5"

action:
  - variables:
      blocks: "{{ state_attr(electricity_price_sensor, 'data') }}"
      prices: "{{ blocks | map(attribute='price') | map('float') | list if blocks else [] }}"
      avg_day: "{{ (prices | sum / prices | length) | round(4) if prices|length >0 else none }}"
      current_price: "{{ states(electricity_price_sensor) | float }}"
      current_hour: "{{ now().hour }}"

  - choose:
      # Laden: prijs lager dan gemiddelde en SOC <100% en tijd binnen user-definities
      - conditions:
          - condition: numeric_state
            entity_id: !input battery_soc_sensor
            below: 100
          - condition: template
            value_template: >
              {{ avg_day is not none and current_price < avg_day }}
          - condition: template
            value_template: >
              {{ current_hour >= load_start_hour and current_hour <= load_end_hour }}
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            below: !input min_solar_day
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch

      # Stoppen als te duur of SOC vol
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: !input battery_soc_sensor
                above: 99
              - condition: template
                value_template: >
                  {{ avg_day is not none and current_price >= avg_day }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input battery_reserve_switch
