blueprint:
  name: "Frank Energie - V36 (New Integration Fix)"
  description: >
    Aangepast voor de nieuwe integratie.
    
    FIX:
    - Tijdzone correctie verwijderd. We nemen de tijd uit de sensor nu 1-op-1 over.
    - Dit lost het probleem op dat uren +1 vooruit liepen.
    
    BEVAT NOG STEEDS:
    - EEPROM Bescherming (30 min draaien), Ochtend Garantie, Tijdsloten, etc.
  domain: automation
  input:
    # --- RAPPORTAGE ---
    report_time_evening:
      name: "Tijdstip Avond Rapport"
      default: "21:30:00"
      selector:
        time:
    report_time_morning:
      name: "Tijdstip Ochtend Rapport"
      default: "08:00:00"
      selector:
        time:
    notify_service_name:
      name: "Notificatie Service"
      description: "Bijv: notify.mobile_app_jouw_naam"
      default: ""
      selector:
        text:

    # --- OCHTEND GARANTIE ---
    target_soc_morning_min:
      name: "Minimale Ochtendbuffer (%)"
      description: "Forceert laden 's nachts tot dit niveau."
      default: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    # --- TIJDSLOTEN ---
    night_start:
      name: "Starttijd Nachtladen"
      default: "00:00:00"
      selector:
        time:
    night_end:
      name: "Eindtijd Nachtladen"
      default: "06:00:00"
      selector:
        time:
    day_start:
      name: "Starttijd Middagladen"
      default: "12:00:00"
      selector:
        time:
    day_end:
      name: "Eindtijd Middagladen"
      default: "15:00:00"
      selector:
        time:

    # --- BASIS ENTITEITEN ---
    battery_reserve_switch:
      name: "Schakelaar: Geforceerd Laden"
      selector:
        entity:
          domain: switch
    battery_soc_sensor:
      name: "Sensor: Batterij SoC (%)"
      selector:
        entity:
          domain: sensor
          device_class: battery
    frank_price_sensor:
      name: "Sensor: Frank Energie Prijzen"
      selector:
        entity:
          domain: sensor

    # --- BOOST ---
    boost_switch:
      name: "Optie: Boost Schakelaar"
      default: []
      selector:
        entity:
          domain: input_boolean

    # --- ZON & SEIZOEN ---
    solar_forecast_today:
      name: "Sensor: Zon VANDAAG"
      selector:
        entity:
          domain: sensor
    solar_forecast_tomorrow:
      name: "Sensor: Zon MORGEN"
      selector:
        entity:
          domain: sensor
    summer_solar_threshold:
      name: "Drempel Zonnige Dag (kWh)"
      default: 15
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "kWh"

    # --- RENDEMENT & DOELEN ---
    min_profit_margin:
      name: "Minimale Winstmarge (%)"
      default: 10
      selector:
        number:
          min: 0
          max: 50
          unit_of_measurement: "%"
    target_soc_winter:
      name: "Doel SoC Winter (%)"
      default: 90
      selector:
        number:
          min: 10
          max: 100
    target_soc_summer:
      name: "Doel SoC Zomer (%)"
      default: 30
      selector:
        number:
          min: 10
          max: 100

    # --- SYSTEEM ---
    battery_capacity_kwh:
      name: "Batterij Capaciteit (kWh)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          step: 0.1
    charge_power_kw:
      name: "Laadsnelheid (kW)"
      default: 3.0
      selector:
        number:
          min: 0.1
          max: 22
          step: 0.1
    safety_factor:
      name: "BMS Vertragingsfactor"
      default: 1.5
      selector:
        number:
          min: 1.0
          max: 4.0
          step: 0.1
    max_price_cap:
      name: "Absolute Max Prijs (â‚¬)"
      default: 0.35
      selector:
        number:
          min: 0
          max: 2.0
          step: 0.01
          mode: box
          unit_of_measurement: "â‚¬"
    emergency_soc:
      name: "Nood SoC (%)"
      default: 10
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

variables:
  # Inputs
  battery_reserve_switch: !input battery_reserve_switch
  battery_soc_sensor: !input battery_soc_sensor
  frank_price_sensor: !input frank_price_sensor
  boost_switch: !input boost_switch
  notify_service_name: !input notify_service_name
  report_time_evening: !input report_time_evening
  report_time_morning: !input report_time_morning
  target_soc_morning_min: !input target_soc_morning_min
  night_start: !input night_start
  night_end: !input night_end
  day_start: !input day_start
  day_end: !input day_end
  solar_forecast_today: !input solar_forecast_today
  solar_forecast_tomorrow: !input solar_forecast_tomorrow
  summer_solar_threshold: !input summer_solar_threshold
  min_profit_margin: !input min_profit_margin
  target_soc_winter: !input target_soc_winter
  target_soc_summer: !input target_soc_summer
  battery_capacity_kwh: !input battery_capacity_kwh
  charge_power_kw: !input charge_power_kw
  safety_factor: !input safety_factor
  max_price_cap: !input max_price_cap
  emergency_soc: !input emergency_soc

trigger:
  - platform: time_pattern
    minutes: "/5"
    id: "timer"
  - platform: time
    at: !input report_time_evening
    id: "report"
  - platform: time
    at: !input report_time_morning
    id: "report"
  - platform: state
    entity_id: !input frank_price_sensor
    id: "price_change"
  - platform: state
    entity_id: !input boost_switch
    to: "on"
    id: "boost"

action:
  - variables:
      current_soc: "{{ states(battery_soc_sensor) | float(0) }}"
      current_price: "{{ states(frank_price_sensor) | float(0) }}"
      is_boost_active: "{{ boost_switch != [] and is_state(boost_switch, 'on') }}"
      should_notify: "{{ notify_service_name | length > 0 }}"

      # --- 1. TIJDSLOT LOGICA ---
      is_in_slot: >-
        {% set now_h = now().hour %}
        {% set ns = night_start.split(':')[0] | int %}
        {% set ne = night_end.split(':')[0] | int %}
        {% set ds = day_start.split(':')[0] | int %}
        {% set de = day_end.split(':')[0] | int %}
        {% if ns > ne %} {% set night_active = (now_h >= ns or now_h < ne) %}
        {% else %}       {% set night_active = (now_h >= ns and now_h < ne) %}
        {% endif %}
        {% if ds > de %} {% set day_active = (now_h >= ds or now_h < de) %}
        {% else %}       {% set day_active = (now_h >= ds and now_h < de) %}
        {% endif %}
        {{ night_active or day_active }}
      
      is_night_now: >-
        {% set now_h = now().hour %}
        {% set ns = night_start.split(':')[0] | int %}
        {% set ne = night_end.split(':')[0] | int %}
        {% if ns > ne %} {{ now_h >= ns or now_h < ne }}
        {% else %}       {{ now_h >= ns and now_h < ne }}
        {% endif %}

      # --- 2. DATA PARSEN (VERSIMPELD VOOR NIEUWE INTEGRATIE) ---
      raw: "{{ state_attr(frank_price_sensor, 'prices') }}"
      prices_json: >-
        {% if raw %}
          {% set text = raw | string %}
          {% set matches = text | regex_findall(
            "datetime\\.datetime\\((\\d+), (\\d+), (\\d+), (\\d+), (\\d+).*?price': ([0-9.]+)"
          ) %}
          [
          {%- for m in matches %}
            {% set y = m[0]|int %}
            {% set mo = m[1]|int %}
            {% set d = m[2]|int %}
            {% set h = m[3]|int %}
            {% set mn = m[4]|int %}
            {% set price = m[5]|float %}
            
            {# AANPASSING V36: GEEN TIJDZONE CONVERSIE MEER #}
            {# We nemen aan dat het uur 'h' al correct is #}
            
            {# We maken wel een timestamp voor de datum-check #}
            {% set raw_dt_str = "%04d-%02d-%02dT%02d:%02d:00" | format(y, mo, d, h, mn) %}
            {% set ts_val = as_timestamp(raw_dt_str) %}
            
            {
              "local_hour": {{ h }},
              "day_str": "{{ 'Vandaag' if d == now().day else 'Morgen' }}",
              "ts": {{ ts_val }},
              "price": {{ price }}
            }{{ "," if not loop.last }}
          {%- endfor %}
          ]
        {% else %} [] {% endif %}

      # --- 3. FILTEREN ---
      filtered_data: >-
        {% set output = namespace(price_list=[], avg=0, slot_data=[], global_sum=0, global_count=0, night_prices=[]) %}
        {% set now_ts = as_timestamp(now()) %}
        {% set history_cutoff = now_ts - 3600 %}
        
        {% if prices_json %}
           {% set ns = night_start.split(':')[0] | int %}
           {% set ne = night_end.split(':')[0] | int %}
           {% set ds = day_start.split(':')[0] | int %}
           {% set de = day_end.split(':')[0] | int %}

           {% for item in prices_json %}
              {% set p_hour = item.local_hour %}
              {% set p_ts = item.ts %}
              
              {# A. Filter Verleden #}
              {% if p_ts >= history_cutoff %}
                  {% set output.global_sum = output.global_sum + item.price %}
                  {% set output.global_count = output.global_count + 1 %}

                  {% set in_night = false %}
                  {% if ns > ne %} {% set in_night = (p_hour >= ns or p_hour < ne) %}
                  {% else %}       {% set in_night = (p_hour >= ns and p_hour < ne) %}
                  {% endif %}
                  
                  {% set in_day = false %}
                  {% if ds > de %} {% set in_day = (p_hour >= ds or p_hour < de) %}
                  {% else %}       {% set in_day = (p_hour >= ds and p_hour < de) %}
                  {% endif %}

                  {% if in_night or in_day %}
                     {% set output.price_list = output.price_list + [item.price] %}
                     {% set output.slot_data = output.slot_data + [item] %}
                  {% endif %}
                  
                  {% if in_night %}
                     {% set output.night_prices = output.night_prices + [item.price] %}
                  {% endif %}
              {% endif %}
           {% endfor %}
        {% endif %}
        
        {% set global_avg = 999.0 %}
        {% if output.global_count > 0 %}
           {% set global_avg = output.global_sum / output.global_count %}
        {% endif %}

        {"all": {{ output.price_list }}, "night": {{ output.night_prices }}, "global_avg": {{ global_avg }}, "slot_data": {{ output.slot_data }}}

      # Variabelen
      sorted_all: "{{ filtered_data.all | sort }}"
      sorted_night: "{{ filtered_data.night | sort }}"
      avg_price_day: "{{ filtered_data.global_avg }}"
      profit_price_limit: "{{ avg_price_day * (1 - (min_profit_margin / 100)) }}"

      # --- 4. ZON & DOEL ---
      forecast_tomorrow_val: "{{ states(solar_forecast_tomorrow) | float(0) }}"
      relevant_solar: >-
        {% if now().hour >= 14 %} {{ forecast_tomorrow_val }}
        {% else %} {{ states(solar_forecast_today) | float(0) }}
        {% endif %}
      dynamic_target_soc: >-
        {% if relevant_solar > summer_solar_threshold %} {{ target_soc_summer }}
        {% else %} {{ target_soc_winter }}
        {% endif %}

      # --- 5. UREN ---
      hours_calc: >-
        {# PLAN A: OCHTEND GARANTIE #}
        {% set deficit_morning = target_soc_morning_min - current_soc %}
        {% if deficit_morning > 0 %}
           {% set kwh_morning = (deficit_morning / 100.0) * battery_capacity_kwh %}
           {% set raw_h = kwh_morning / charge_power_kw %}
           {% set h_morning = (raw_h * safety_factor) | round(0, 'ceil') | int %}
        {% else %}
           {% set h_morning = 0 %}
        {% endif %}

        {# PLAN B: TOTAAL DOEL #}
        {% set deficit_total = dynamic_target_soc - current_soc %}
        {% if deficit_total > 0 %}
           {% set kwh_total = (deficit_total / 100.0) * battery_capacity_kwh %}
           {% set strict = (kwh_total / charge_power_kw) | round(0, 'ceil') | int %}
           {% set safe = (strict * safety_factor) | round(0, 'ceil') | int %}
        {% else %}
           {% set strict = 0 %}
           {% set safe = 0 %}
        {% endif %}
        {"morning": {{ h_morning }}, "strict": {{ strict }}, "safe": {{ safe }}}

      hours_morning: "{{ hours_calc.morning }}"
      hours_strict: "{{ hours_calc.strict }}"
      hours_safe: "{{ hours_calc.safe }}"

      # --- 6. DREMPELS ---
      threshold_morning: >-
        {% if sorted_night | length > 0 and hours_morning > 0 %}
           {% set idx = (hours_morning - 1) if (hours_morning - 1) < sorted_night|length else (sorted_night|length - 1) %}
           {{ sorted_night[idx] }}
        {% else %} -999 {% endif %}

      threshold_strict: >-
        {% if sorted_all | length > 0 and hours_strict > 0 %}
           {% set idx = (hours_strict - 1) if (hours_strict - 1) < sorted_all|length else (sorted_all|length - 1) %}
           {{ sorted_all[idx] }}
        {% else %} -999 {% endif %}

      threshold_safe: >-
        {% if sorted_all | length > 0 and hours_safe > 0 %}
           {% set idx = (hours_safe - 1) if (hours_safe - 1) < sorted_all|length else (sorted_all|length - 1) %}
           {{ sorted_all[idx] }}
        {% else %} -999 {% endif %}

  - choose:
      # --- RAPPORTAGE TRIGGER ---
      - conditions:
          - condition: trigger
            id: "report"
        sequence:
          - if:
              - condition: template
                value_template: "{{ should_notify }}"
            then:
              - service: !input notify_service_name
                data:
                  message: >-
                    ðŸ“Š **Batterij Laadplan**
                    
                    ðŸ”‹ **Status**
                    Huidig: {{ current_soc }}% -> Doel: {{ dynamic_target_soc }}%
                    Ochtend Buffer: {{ target_soc_morning_min }}%
                    
                    ðŸ’° **Financieel**
                    Strikt (<): â‚¬{{ threshold_strict | round(3) }}
                    Buffer (<): â‚¬{{ profit_price_limit | round(3) }}
                    Ochtend (<): â‚¬{{ threshold_morning | round(3) }}
                    
                    ðŸ•’ **Geplande Starttijden**
                    {%- set ns_list = namespace(found=[]) %}
                    {%- for item in filtered_data.slot_data %}
                      {%- if item.price <= threshold_strict %}
                        {%- set ns_list.found = ns_list.found + [item.day_str ~ " " ~ item.local_hour ~ ":00 (â‚¬" ~ item.price|round(3) ~ ")"] %}
                      {%- elif item.price <= threshold_safe and item.price < profit_price_limit %}
                        {%- set ns_list.found = ns_list.found + [item.day_str ~ " " ~ item.local_hour ~ ":00 (Buffer)"] %}
                      {%- endif %}
                    {%- endfor %}
                    {{ ns_list.found | join('\n') if ns_list.found else "Geen geschikte uren gevonden." }}
                    {% else %}
                    â›” Geen komende laad-uren meer beschikbaar in de data.
                    {% endif %}

      # --- BOOST ---
      - conditions:
          - condition: trigger
            id: "boost"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input battery_reserve_switch
          - if:
              - condition: template
                value_template: "{{ should_notify }}"
            then:
              - service: !input notify_service_name
                data:
                  message: "ðŸš€ Boost geactiveerd!"

      # --- NOOD ---
      - conditions:
          - condition: template
            value_template: "{{ current_soc < emergency_soc }}"
          - condition: template
            value_template: "{{ current_price < (max_price_cap * 1.5) }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              - if:
                  - condition: template
                    value_template: "{{ should_notify }}"
                then:
                  - service: !input notify_service_name
                    data:
                      message: "âš ï¸ Noodlading gestart."

      # --- SLIM LADEN ---
      - conditions:
          - condition: or
            conditions:
              # 1. OCHTEND GARANTIE
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ is_night_now }}"
                  - condition: template
                    value_template: "{{ current_price <= threshold_morning }}"
              # 2. TOTAAL STRIKT
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ is_in_slot }}"
                  - condition: template
                    value_template: "{{ current_price <= threshold_strict }}"
              # 3. BUFFER
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ is_in_slot }}"
                  - condition: template
                    value_template: "{{ current_price <= threshold_safe }}"
                  - condition: template
                    value_template: "{{ current_price < profit_price_limit }}"
          
          # Veiligheid
          - condition: template
            value_template: "{{ current_price < max_price_cap }}"
          - condition: template
            value_template: "{{ current_soc < dynamic_target_soc }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ is_state(battery_reserve_switch, 'off') }}"
            then:
              - service: switch.turn_on
                target:
                  entity_id: !input battery_reserve_switch
              # NOTIFICATIE (MAX 1x per uur)
              - if:
                  - condition: template
                    value_template: "{{ should_notify }}"
                  - condition: template
                    value_template: >-
                      {% if states[battery_reserve_switch].last_changed %}
                        {{ (as_timestamp(now()) - as_timestamp(states[battery_reserve_switch].last_changed)) > 3600 }}
                      {% else %} true {% endif %}
                then:
                  - service: !input notify_service_name
                    data:
                      message: >-
                        ðŸ”‹ Slim laden gestart! 
                        Prijs: â‚¬{{ current_price | round(3) }}

      # --- STOPPEN (EEPROM BESCHERMING) ---
      - conditions:
          - condition: template
            value_template: "{{ is_state(battery_reserve_switch, 'on') }}"
        sequence:
          - if:
              - condition: or
                conditions:
                  - condition: template
                    value_template: >-
                      {% if states[battery_reserve_switch].last_changed %}
                        {{ (as_timestamp(now()) - as_timestamp(states[battery_reserve_switch].last_changed)) > 1800 }}
                      {% else %} true {% endif %}
                  - condition: template
                    value_template: "{{ current_soc >= dynamic_target_soc }}"
            then:
              - service: switch.turn_off
                target:
                  entity_id: !input battery_reserve_switch

mode: single